export const PORT_VERSION = "0.1.0";

export const PARITY_MILESTONES = [
  {
    stage: 1,
    name: "Local runtime and session persistence",
    status: "implemented-with-limitations",
    features: [
      "TypeScript Deep Agents graph with filesystem tools, bounded local shell execution, cancellation, and approval resume",
      "Atomic checkpoints and single-writer session ownership",
      "Explicit recover-lock refuses live/foreign owners and preserves dead-owner lock files in recovery archives",
      "Python JSON and SQLite MessagePack conversation import into a new TypeScript session without executing Python constructors",
      "Archive picker and confirmed restore into a new idle session without overwriting the source or replaying tools",
    ],
    limitations: [
      "Local execution is not a security sandbox",
      "Checkpoints remain full snapshots capped at 64 MiB; uncheckpointed tool effects can replay after cancellation or a crash",
      "Python import is conversation-only: tasks, pending writes, approvals, billing state, and arbitrary/delta-serialized Python objects are not migrated",
      "Archive restore currently accepts supported text-message shapes and requires matched tool calls/results; goals and billing state stay in the original session",
      "Malformed locks, foreign-host locks, reused live PIDs, and crash-stale recovery guards require operator inspection",
    ],
  },
  {
    stage: 2,
    name: "Terminal UI, commands, and client/server transport",
    status: "partial",
    features: [
      "Child-process server with validated IPC, run/event IDs, acknowledgements, bounded replay, heartbeat, detach and attach",
      "Prompt queue, restart, thread/model/agent/skill pickers, multiline composer, scrollback, and approval previews",
      "Structured transcript entries with correlated tool calls and results, per-tool renderers, unified diffs shared with the approval preview, and hand-rolled markdown with basic syntax highlighting",
      "Semantic theme tokens, unicode/ascii charset selection, a segmented footer that degrades with terminal width, and a git branch read from .git/HEAD without a subprocess",
      "Composer @ file completion, ! shell shorthand routed through normal approvals, and a slash dropdown with descriptions",
      "Goal/rubric commands, command completion, export, editor, clipboard, theme, and session controls",
      "All public upstream command names are represented, with explicitly documented TypeScript-specific semantics",
      "Confirmed npm update plans verify installation identity and release age; source checkouts and unbound distributions never self-update",
      "Pre-session auto-update supports opt-out and a first-launch notice; successful updates exit before starting a session",
    ],
    limitations: [
      "Command-name coverage is not full upstream command semantics: optional integrations use native plugins, not Python package extras",
      "The public npm distribution identity is unconfirmed; live installation/update has not been exercised",
      "Automatic updates require restarting the application afterward; automatic process re-execution is not implemented",
      "Full terminal accessibility, user-defined upstream theme files, hidden debug commands, notifications settings, and provider/auth workflows remain incomplete",
      "Markdown and highlighting are hand-rolled: emphasis does not nest, and only JavaScript/TypeScript, Python, and shell families are highlighted",
      "The reasoning peek renders standard reasoning content blocks; no configured provider has been observed emitting them, so it is unexercised end to end",
      "No context-window percentage is shown: per-model context limits are not available and character counts do not imply tokenization",
      "Real-provider streaming and exhaustive disconnect/crash/nested-cancellation scenarios remain unverified",
    ],
  },
  {
    stage: 3,
    name: "Configuration, model controls, and goal lifecycle",
    status: "partial",
    features: [
      "Layered JSON configuration, provenance, last-good snapshots, session overrides, and user JSON writes",
      "Expanded typed TOML/environment compatibility for implemented settings; invalid supported scalar values fall back without discarding valid siblings",
      "Update preferences, native-extension enablement, memory policy, explicit Auto-mode criteria acceptance, thread display/sort, and session-cost warnings",
      "Named OpenAI-compatible providers, endpoint-bound credentials, separate grader/classifier/summary models, and conversation-preserving model changes",
      "Manual approvals, read-only Plan mode that rejects shell and filesystem changes with feedback, restricted classifier-backed Auto, and explicitly acknowledged session-scoped YOLO",
      "Durable usage/cost accounting, memory/goals, explicit compaction, and conversation archives",
      "Automatic goal/rubric grading and bounded revision retain normal approvals; next-turn rubrics survive pauses and restore prior session criteria",
    ],
    limitations: [
      "This is not the full upstream manifest: unsupported settings are rejected instead of silently accepted",
      "TOML remains read-only; /config user writes and /auto-update persistence require a JSON user configuration",
      "Native Anthropic/Google adapters, provider OAuth, interpreter/PTC, remote sandbox settings, onboarding, and broader upstream behavior remain pending",
      "Goal assessments use recorded conversation evidence, not a separate repository-inspecting grader; unknown evidence never counts as met",
      "Usage is completed-request accounting, not authoritative billing; prices remain user-configured and missing prices remain unknown",
      "Explicit compaction accepts at most 300,000 conversation characters",
    ],
  },
  {
    stage: 4,
    name: "Hooks, native extensions, and marketplaces",
    status: "partial",
    features: [
      "Explicitly trusted MCP stdio/HTTP tools with inherited approval gates and idle-boundary rebuilds",
      "Lifecycle hooks with bounded execution, cancellation, matcher handling, transcript context, and run-time terminal output validation",
      "Native bundled .mjs extension registration for tools, middleware, backend routes, agents, skills, and shutdown cleanup",
      "Failed setup rolls back registrations; dynamically added tools remain approval-gated and agent-scoped",
      "Local JSON/HTTPS native marketplaces with checksum-pinned snapshots, reviewed install/update, enable/disable, and uninstall retaining snapshots/data",
      "Plugin registry mutations block subsequent runs until integrations successfully reload or the server restarts",
      "Web tools remain default-off and public fetches validate addresses, redirects, DNS, timeouts, and response limits",
    ],
    limitations: [
      "Native TypeScript equivalents were selected intentionally; existing Python extension source requires porting",
      "Git/GitHub marketplaces, all upstream manifest/component formats, loose-file/entry-point discovery, and plugin auto-update remain incomplete",
      "Native entries must be bundled .mjs; backend and middleware registrations made after setup require a rebuild",
      "Terminal output is wired during runs only; complete startup/shutdown/compaction UI delivery and remaining hook output semantics are pending",
      "MCP OAuth, SSE, live tool-list refresh, remote sandboxes, ACP, and broader diagnostics remain pending",
      "Remote marketplace installation and real external integrations have not been verified",
    ],
  },
] as const;
