export const COMMANDS = [
  { name: "help", aliases: [], bypass: "always", description: "Show slash commands and keyboard controls" },
  { name: "skills", aliases: [], bypass: "picker", description: "Browse project, user, and plugin skills" },
  { name: "skill", aliases: [], bypass: "queued", description: "Invoke a skill: /skill name [request] or /skill:name" },
  { name: "skill-creator", aliases: [], bypass: "queued", description: "Create or refine a reusable skill through normal approvals" },
  { name: "trace", aliases: [], bypass: "queued", description: "Open the latest explicitly recorded LangSmith trace" },
  { name: "docs", aliases: [], bypass: "always", description: "Open the upstream documentation" },
  { name: "changelog", aliases: [], bypass: "always", description: "Open the upstream changelog" },
  { name: "feedback", aliases: [], bypass: "always", description: "Open the upstream issue tracker; does not submit a report" },
  { name: "clear", aliases: [], bypass: "queued", description: "Start a fresh session; keep the previous one" },
  { name: "force-clear", aliases: [], bypass: "always", description: "Cancel and drain current work, then start a fresh session" },
  { name: "threads", aliases: [], bypass: "picker", description: "Browse sessions; /threads -r [id] resumes" },
  { name: "resume", aliases: [], bypass: "queued", description: "Resume a session by ID or unambiguous prefix" },
  { name: "continue", aliases: [], bypass: "always", description: "Continue unfinished work or review pending approvals" },
  { name: "history", aliases: [], bypass: "queued", description: "Show the current conversation" },
  { name: "prompts", aliases: [], bypass: "always", description: "Recall a prompt into the composer without sending it" },
  { name: "queue", aliases: [], bypass: "always", description: "Inspect queued prompts; pause, resume, clear, edit N, remove N" },
  { name: "cancel", aliases: [], bypass: "always", description: "Pause the queue and cancel active work" },
  { name: "detach", aliases: [], bypass: "always", description: "Leave the server running for later --attach (15 minute grace)" },
  { name: "restart", aliases: [], bypass: "always", description: "Drain and restart the server without replaying tools" },
  { name: "rename", aliases: [], bypass: "queued", description: "Set this session's display title" },
  { name: "export", aliases: [], bypass: "queued", description: "Export conversation JSON to a new file: /export <path>" },
  { name: "copy", aliases: [], bypass: "queued", description: "Copy the latest assistant answer to the system clipboard" },
  { name: "editor", aliases: [], bypass: "queued", description: "Compose in VISUAL/EDITOR, returning a draft without sending" },
  { name: "tokens", aliases: [], bypass: "queued", description: "Show retained context and durable token usage" },
  { name: "context", aliases: [], bypass: "queued", description: "Show retained conversation size and usage" },
  { name: "context-doctor", aliases: [], bypass: "queued", description: "Audit configured context, agents, tool schemas, and memory" },
  { name: "tools", aliases: [], bypass: "queued", description: "Show configured and observed runtime tools" },
  { name: "extensions", aliases: [], bypass: "queued", description: "Inspect trusted extension contributions and provenance" },
  { name: "mcp", aliases: [], bypass: "queued", description: "Inspect MCP; reconnect, enable <server>, disable <server>" },
  { name: "plugins", aliases: [], bypass: "queued", description: "Manage marketplaces and install, update, enable, disable, or uninstall plugins" },
  { name: "agents", aliases: [], bypass: "picker", description: "Pick the root agent or /agents clear for the default" },
  { name: "model", aliases: [], bypass: "picker", description: "Pick or switch model: /model [provider:]model" },
  { name: "effort", aliases: [], bypass: "queued", description: "Set reasoning effort: low, medium, high, clear" },
  { name: "summarization-model", aliases: [], bypass: "picker", description: "Pick a separate summary model, or clear to inherit" },
  { name: "auth", aliases: ["connect"], bypass: "queued", description: "Show credential source; /auth set opens masked input" },
  { name: "config", aliases: [], bypass: "queued", description: "Inspect settings; /config set [--user] key <JSON>; unset key" },
  { name: "reload", aliases: [], bypass: "queued", description: "Reload config and trusted integrations at an idle boundary" },
  { name: "manual", aliases: [], bypass: "always", description: "Immediately require human approval for future gated actions" },
  { name: "auto", aliases: [], bypass: "queued", description: "Classifier-backed edits; other actions require review" },
  { name: "yolo", aliases: [], bypass: "queued", description: "Open explicit unrestricted-mode acknowledgement" },
  { name: "cost", aliases: ["costs"], bypass: "queued", description: "Show durable model usage and known/unknown costs" },
  { name: "compact", aliases: ["offload"], bypass: "queued", description: "Archive and summarize idle conversation" },
  { name: "archives", aliases: [], bypass: "queued", description: "Browse archives or restore <id> into a new session" },
  { name: "memory", aliases: [], bypass: "queued", description: "Read memory, set <text>, or clear" },
  { name: "remember", aliases: [], bypass: "queued", description: "Append explicit trusted context to session memory" },
  { name: "goal", aliases: [], bypass: "queued", description: "Set objective | criteria; show, pause, resume, complete, clear" },
  { name: "rubric", aliases: ["criteria"], bypass: "queued", description: "Show or set the current goal's acceptance criteria" },
  { name: "theme", aliases: [], bypass: "picker", description: "Select dark, light, or plain terminal colors" },
  { name: "scrollbar", aliases: [], bypass: "queued", description: "Toggle scroll position display" },
  { name: "timestamps", aliases: [], bypass: "queued", description: "Toggle timestamps for new transcript messages" },
  { name: "line-numbers", aliases: [], bypass: "queued", description: "Toggle approval-preview line numbers" },
  { name: "notifications", aliases: [], bypass: "always", description: "Show recent connection, runtime, and hook notices" },
  { name: "parity", aliases: [], bypass: "always", description: "Show exact implemented features and remaining gaps" },
  { name: "install", aliases: [], bypass: "queued", description: "Install an optional native integration: <name@marketplace>" },
  { name: "uninstall", aliases: [], bypass: "queued", description: "Uninstall an optional native integration; retain snapshots and data" },
  { name: "update", aliases: [], bypass: "queued", description: "Check and review updates for the confirmed npm distribution" },
  { name: "auto-update", aliases: [], bypass: "queued", description: "Inspect or toggle pre-session auto-updates; source installs never self-update" },
  { name: "version", aliases: ["about"], bypass: "always", description: "Show the TypeScript port version" },
  { name: "quit", aliases: ["q", "exit"], bypass: "always", description: "Exit, drain the server, and preserve the session" },
] as const;
export type CommandName = typeof COMMANDS[number]["name"];

export function parseCommand(input: string): { name: CommandName | null; argument: string; bypass: "always" | "queued" | "picker" } | null {
  if (!input.startsWith("/")) return null;
  const match = /^\/([^\s]+)\s*([\s\S]*)$/u.exec(input);
  const name = match?.[1]?.toLowerCase() ?? "";
  if (name.startsWith("skill:")) return { name: "skill", argument: `${name.slice(6)} ${match?.[2] ?? ""}`.trim(), bypass: "queued" };
  const command = COMMANDS.find((entry) => entry.name === name || (entry.aliases as readonly string[]).includes(name));
  return { name: command?.name ?? null, argument: match?.[2] ?? "", bypass: command?.bypass ?? "always" };
}
